server {
    listen 80;
    # server_name localhost;
    server_name filedrive-ctx.pages.dev; # production

    location /api {
        proxy_pass http://go_backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Add CORS headers so the Frontend can talk to the Backend
        add_header 'Access-Control-Allow-Origin' 'https://filedrive-ctx.pages.dev' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;

        # Handle Preflight requests
        if ($request_method = 'OPTIONS') {
            return 204;
        }
    }
}